name: CD

on:
  push:
    branches: main

jobs:
  cd:
    name: Pages delivery
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2

      - name: Angular Deploy to gh-pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: production
          base_href: /CovidAnalysis/
          run_lint: "true"
          deploy_branch: gh-pages
          angular_project_dir: client/
          angular_dist_build_folder: client/dist/covidanalysis
