# Generates a new release with updated data every day ay midnight

name: Daily Release

# schedule the chart generation to be executed every day at midnight
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with Open Data Submodule # updates gvt repo submodule for publication
      uses: actions/checkout@v2
      with:
        submodules: 'recursive' 
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pandas
        pip install numpy
        pip install matplotlib
        pip install python-dateutil
    
    - name: Generate updated charts
      run: |
        python generate_charts.py
        
    - name: Save charts artifacts
      uses: actions/upload-artifact@v2
      with:
        name: charts
        path: ./docs/

    # Useful to create the release name
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: covid-${{ steps.date.outputs.date }}
        release_name: Release ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      id: upload-release-assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create-release.outputs.id }}
        assets_path: ./docs